### ISSUE TITLE
Containers stuck in "ContainerCreating" status when following "Virtualized Kuberenetes Cluster" ROS1 example

### ISSUE THREAD

**Issue by rfzeg** [fujitatomoya/ros_k8s#24] opened 2023-04-19 10:43 UTC
Hello,
I am doing my best to complete the steps to have a Virtualized Kuberenetes Cluster ROS1 example running on my local machine.
However after the deployment step my pods reach the status "ContainerCreating" and stay there. I cannot figure out why they are not in status "READY".

This is the complete list of commands that I run in sequence:  

```
# List the running containers
docker ps
```
No containers show

This  creates a cluster without errors:
```
kind create cluster --config=kind-multiple-node.yaml
```
Running:
```
docker ps
```
 Shows two docker containers with NAMES 'control-plane' and 'worker'

This command:
```
kubectl get node
```

Shows two Kubernetes nodes, one 'control-plane' and one 'worker' like so:
```
NAME                 STATUS   ROLES           AGE   VERSION
kind-control-plane   Ready    control-plane   18h   v1.25.2
kind-worker          Ready    <none>          18h   v1.25.2
```
    
Deploy a CNI plugin:
```
kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
```

Deploy ROS nodes
```
kubectl apply -f ros1-daemonset.yaml
```

Display the Kubernetes pods:
```
kubectl get pods
```

Produces this result:
```
NAME                   READY   STATUS              RESTARTS   AGE
ros1-deamonset-7pdtl   0/3     ContainerCreating   0          65m
ros1-deamonset-g2fn9   0/3     ContainerCreating   0          65m
```

STATUS is "ContainerCreating" indicating that Kubernetes is still in the process of creating the containers for the pods.

I have waited for over 65 minutes and the status does not change.

Am I missing something?

Here is a capture of the sequence of commands that I run (video was speeded up):

![kubernetes_deploy_ros_nodes](https://user-images.githubusercontent.com/40167051/233051031-aa96b015-8e57-44b0-9446-7c93bc38b03a.gif)

Thank you very much!

**Comment by fujitatomoya** [comment] 2023-04-19 16:06
@rfzeg thanks for creating issue, i will take a look. i have never had that experience, probably some hardware capability or resource related, will get you back.

**Comment by fujitatomoya** [comment] 2023-04-21 06:05
@rfzeg confirmed that i can reproduce this issue, i will check what is going on here.

**Comment by fujitatomoya** [comment] 2023-04-21 06:19
The root cause is that bridge CNI plugin does not exist, so that flannel cannot initialize to create bridge interface to connect veth to host network namespace.

```bash
tomoyafujita@~/DVT/github.com/fujitatomoya/ros_k8s/yaml >kubectl get nodes -o wide
NAME                 STATUS   ROLES           AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
kind-control-plane   Ready    control-plane   100s   v1.25.2   172.18.0.3    <none>        Ubuntu 22.04.1 LTS   5.15.0-69-generic   containerd://1.6.8
kind-worker          Ready    <none>          76s    v1.25.2   172.18.0.2    <none>        Ubuntu 22.04.1 LTS   5.15.0-69-generic   containerd://1.6.8
tomoyafujita@~/DVT/github.com/fujitatomoya/ros_k8s/yaml >kubectl apply -f ros1-daemonset.yaml
daemonset.apps/ros1-deamonset created
tomoyafujita@~/DVT/github.com/fujitatomoya/ros_k8s/yaml >kubectl get pods -w
NAME                   READY   STATUS              RESTARTS   AGE
ros1-deamonset-2xv9l   0/3     ContainerCreating   0          6s
ros1-deamonset-lfvm2   0/3     ContainerCreating   0          6s

...
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               109s  default-scheduler  Successfully assigned default/ros1-deamonset-2xv9l to kind-worker
  Warning  FailedCreatePodSandBox  108s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "aac42796edf952ecc5532867536675716c87949b14a6ef76cbd670d7f36d0e63": plugin type="flannel" failed (add): failed to delegate add: failed to find plugin "bridge" in path [/opt/cni/bin]
  Warning  FailedCreatePodSandBox  94s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "dd602b1a2f792bec323781a3591984b4a5d5aa2764499780db932a0df3b08ddb": plugin type="flannel" failed (add): failed to delegate add: failed to find plugin "bridge" in path [/opt/cni/bin]

tomoyafujita@~/DVT >docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS                       NAMES
1e6f87025225   kindest/node:v1.25.2   "/usr/local/bin/entr…"   15 minutes ago   Up 15 minutes   127.0.0.1:39279->6443/tcp   kind-control-plane
88e0e2a4cf76   kindest/node:v1.25.2   "/usr/local/bin/entr…"   15 minutes ago   Up 15 minutes                               kind-worker

tomoyafujita@~/DVT >docker exec 1e6f87025225 ls -lt /opt/cni/bin
total 16272
-rwxr-xr-x 1 root root 2342446 Apr 21 05:53 flannel
-rwxr-xr-x 1 root root 3241605 Mar  9  2022 host-local
-rwxr-xr-x 1 root root 4092460 Mar  9  2022 ptp
-rwxr-xr-x 1 root root 3295519 Mar  9  2022 loopback
-rwxr-xr-x 1 root root 3679140 Mar  9  2022 portmap
```

**Comment by fujitatomoya** [comment] 2023-04-21 07:23
addressed by https://github.com/fujitatomoya/ros_k8s/commit/a92776ea954680521ec9934950ed367d369feca4

especially you can refer to https://github.com/fujitatomoya/ros_k8s/commit/a92776ea954680521ec9934950ed367d369feca4

btw, KIND nodes will docker pull the images like 3GB for each virtualized instances, this would take several minutes.

```bash
tomoyafujita@~/DVT/github.com/fujitatomoya/ros_k8s/yaml >kubectl get pods -w
NAME                   READY   STATUS              RESTARTS   AGE
ros1-deamonset-glx6p   0/3     ContainerCreating   0          9s
ros1-deamonset-xjpfw   0/3     ContainerCreating   0          9s
ros1-deamonset-glx6p   3/3     Running             0          4m35s
ros1-deamonset-xjpfw   3/3     Running             0          4m35s
```

**Comment by fujitatomoya** [comment] 2023-04-21 07:24
@rfzeg i confirmed that it is addressed, if you can check with your environment, that would be appreciated. and please go ahead to close this issue once confirmed.

**Closed** 2023-04-21 23:12 UTC
